// northwindAngular/src/app/components/layout-area/layout/layout.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-layout', // element name: <app-layout></app-layout>
    templateUrl: './layout.component.html',
    styleUrls: ['./layout.component.css']
})
export class LayoutComponent implements OnInit {

    constructor() { }

    ngOnInit(): void {
    }

}


<div>
  <header>
    <app-header></app-header>
  </header>
  <aside>
    <app-menu></app-menu>
  </aside>
  <main>
    <router-outlet></router-outlet>
  </main>
  <footer>
    <app-footer></app-footer>
  </footer>
</div>

// northwind/src/Components/LayoutArea/Layout/Layout.tsx
import React from 'react';
import Header from '../Header/Header';
import Footer from '../Footer/Footer';
import Menu from '../Menu/Menu';
import './Layout.css';
import Home from '../../HomeArea/Home/Home';

export default function Layout(): JSX.Element {
  return (
    <div className="Layout">
      <header>
        <Header />
      </header>
      <aside>
        <Menu />
      </aside>
      <main>
        <Home />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
