// p25-hw/src/Components/Layout/Layout.tsx
import React from 'react';
import Aside from '../Aside/Aside';
import Footer from '../Footer/Footer';
import Header from '../Header/Header';
import Routing from '../Routing/Routing';
import './Layout.css';
export default function Layout(): JSX.Element {
  return (
    <div className="Layout">
      <header className="header">
        <Header />
      </header>
      <aside className="aside">
        <Aside />
      </aside>
      <main className="main">
        <Routing />
      </main>
      <footer className="footer">
        <Footer />
      </footer>
    </div>
  );
}

// northwindAngular/src/app/components/layout-area/layout/layout.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-layout', // element name: <app-layout></app-layout>
    templateUrl: './layout.component.html',
    styleUrls: ['./layout.component.css']
})
export class LayoutComponent implements OnInit {

    constructor() { }

    ngOnInit(): void {
    }

}


<div>
  <header>
    <app-header></app-header>
  </header>
  <aside>
    <app-menu></app-menu>
  </aside>
  <main>
    <router-outlet></router-outlet>
  </main>
  <footer>
    <app-footer></app-footer>
  </footer>
</div>
