// northwindAngular/src/app/components/layout-area/layout/layout.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-layout', // element name: <app-layout></app-layout>
    templateUrl: './layout.component.html',
    styleUrls: ['./layout.component.css']
})
export class LayoutComponent implements OnInit {

    constructor() { }

    ngOnInit(): void {
    }

}


<div>
  <header>
    <app-header></app-header>
  </header>
  <aside>
    <app-menu></app-menu>
  </aside>
  <main>
    <router-outlet></router-outlet>
  </main>
  <footer>
    <app-footer></app-footer>
  </footer>
</div>

// 01 - Northwind/src/Components/LayoutArea/Layout/Layout.tsx
import Footer from "../Footer/Footer";
import Header from "../Header/Header";
import Menu from "../Menu/Menu";
import Routing from "../Routing/Routing";
import "./Layout.css";

function Layout(): JSX.Element {
    return (
        <div className="Layout">
            <header>
                <Header />
            </header>
            <aside>
                <Menu />
            </aside>
            <main>
                <Routing />
            </main>
            <footer>
                <Footer />
            </footer>
        </div>
    );
}

export default Layout;
