// northwindAngular/src/app/components/products-area/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductModel } from 'src/app/models/product-model';
import { ProductsService } from 'src/app/services/products.service';

@Component({
    selector: 'app-product-list',
    templateUrl: './product-list.component.html',
    styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {

    public products: ProductModel[];

    constructor(private productsService: ProductsService) { } // DI

    async ngOnInit() {
        try {
            this.products = await this.productsService.getAllProducts();
        }
        catch(err: any) {
            alert(err.message);
        }
    }

}

<div>

    <!-- <span *ngFor="let p of products">{{p.name}} | </span> -->
    <app-product-card *ngFor="let p of products" [product]="p"></app-product-card>

</div>

// 01 - Northwind/src/Components/ProductsArea/ProductList/ProductList.tsx
import { useEffect, useState } from "react";
import ProductModel from "../../../Models/ProductModel";
import productsService from "../../../Services/ProductsService";
import "./ProductList.css";

function ProductList(): JSX.Element {

    // State to handle products: 
    const [products, setProducts] = useState<ProductModel[]>([]);

    // Get products from backend once:
    useEffect(() => {
        productsService.getAllProducts()
            .then(products => setProducts(products))
            .catch(err => alert(err.message));
    }, []);

    return (
        <div className="ProductList">

            {/* Display name + price in a border */}
            {products.map(p =>
                <div className="Box">
                    <span>{p.name} (${p.price})</span>
                </div>
            )}

        </div>
    );
}

export default ProductList;
